export const TypeInstitution = {
  MINISTERE: 'MINISTERE',
  ETABLISSEMENT_PUBLIC_ADMINISTRATIF: 'ETABLISSEMENT_PUBLIC_ADMINISTRATIF',
  ETABLISSEMENT_PUBLIC_COMMERCIAL: 'ETABLISSEMENT_PUBLIC_COMMERCIAL',
  COLLECTIVITE_LOCALE: 'COLLECTIVITE_LOCALE',
  SECTEUR_PRIVE: 'SECTEUR_PRIVE',
  ORGANISATION_INTERNATIONALE: 'ORGANISATION_INTERNATIONALE',
  ONG: 'ONG',
  UNIVERSITE: 'UNIVERSITE',
  AUTRE: 'AUTRE',
} as const;

export type TypeInstitution = (typeof TypeInstitution)[keyof typeof TypeInstitution];
