package com.convention.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClientEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientEntityAllPropertiesEquals(ClientEntity expected, ClientEntity actual) {
        assertClientEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertClientEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientEntityAllUpdatablePropertiesEquals(ClientEntity expected, ClientEntity actual) {
        assertClientEntityUpdatableFieldsEquals(expected, actual);
        assertClientEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientEntityAutoGeneratedPropertiesEquals(ClientEntity expected, ClientEntity actual) {
        assertThat(actual)
            .as("Verify ClientEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientEntityUpdatableFieldsEquals(ClientEntity expected, ClientEntity actual) {
        assertThat(actual)
            .as("Verify ClientEntity relevant properties")
            .satisfies(a -> assertThat(a.getNumClient()).as("check numClient").isEqualTo(expected.getNumClient()))
            .satisfies(a -> assertThat(a.getNomClient()).as("check nomClient").isEqualTo(expected.getNomClient()))
            .satisfies(a -> assertThat(a.getAdresseClient()).as("check adresseClient").isEqualTo(expected.getAdresseClient()))
            .satisfies(a -> assertThat(a.getEmailClient()).as("check emailClient").isEqualTo(expected.getEmailClient()))
            .satisfies(a -> assertThat(a.getWhatsClient()).as("check whatsClient").isEqualTo(expected.getWhatsClient()))
            .satisfies(a -> assertThat(a.getObsClient()).as("check obsClient").isEqualTo(expected.getObsClient()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientEntityUpdatableRelationshipsEquals(ClientEntity expected, ClientEntity actual) {
        // empty method
    }
}
