package com.convention.domain;

import static com.convention.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ConventionEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConventionEntityAllPropertiesEquals(ConventionEntity expected, ConventionEntity actual) {
        assertConventionEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertConventionEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConventionEntityAllUpdatablePropertiesEquals(ConventionEntity expected, ConventionEntity actual) {
        assertConventionEntityUpdatableFieldsEquals(expected, actual);
        assertConventionEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConventionEntityAutoGeneratedPropertiesEquals(ConventionEntity expected, ConventionEntity actual) {
        assertThat(actual)
            .as("Verify ConventionEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConventionEntityUpdatableFieldsEquals(ConventionEntity expected, ConventionEntity actual) {
        assertThat(actual)
            .as("Verify ConventionEntity relevant properties")
            .satisfies(a -> assertThat(a.getNumConvention()).as("check numConvention").isEqualTo(expected.getNumConvention()))
            .satisfies(a -> assertThat(a.getDateSignConv()).as("check dateSignConv").isEqualTo(expected.getDateSignConv()))
            .satisfies(a -> assertThat(a.getDateDebutConv()).as("check dateDebutConv").isEqualTo(expected.getDateDebutConv()))
            .satisfies(a -> assertThat(a.getPeriodeEcheance()).as("check periodeEcheance").isEqualTo(expected.getPeriodeEcheance()))
            .satisfies(a ->
                assertThat(a.getRedevance()).as("check redevance").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRedevance())
            )
            .satisfies(a -> assertThat(a.getNomResponsable()).as("check nomResponsable").isEqualTo(expected.getNomResponsable()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()))
            .satisfies(a -> assertThat(a.getDateModification()).as("check dateModification").isEqualTo(expected.getDateModification()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConventionEntityUpdatableRelationshipsEquals(ConventionEntity expected, ConventionEntity actual) {
        assertThat(actual)
            .as("Verify ConventionEntity relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()));
    }
}
