package com.convention.domain;

import static com.convention.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DetailFactureEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailFactureEntityAllPropertiesEquals(DetailFactureEntity expected, DetailFactureEntity actual) {
        assertDetailFactureEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertDetailFactureEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailFactureEntityAllUpdatablePropertiesEquals(DetailFactureEntity expected, DetailFactureEntity actual) {
        assertDetailFactureEntityUpdatableFieldsEquals(expected, actual);
        assertDetailFactureEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailFactureEntityAutoGeneratedPropertiesEquals(DetailFactureEntity expected, DetailFactureEntity actual) {
        assertThat(actual)
            .as("Verify DetailFactureEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailFactureEntityUpdatableFieldsEquals(DetailFactureEntity expected, DetailFactureEntity actual) {
        assertThat(actual)
            .as("Verify DetailFactureEntity relevant properties")
            .satisfies(a -> assertThat(a.getDesignation()).as("check designation").isEqualTo(expected.getDesignation()))
            .satisfies(a ->
                assertThat(a.getPrixUnitaire())
                    .as("check prixUnitaire")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrixUnitaire())
            )
            .satisfies(a -> assertThat(a.getQuantite()).as("check quantite").isEqualTo(expected.getQuantite()))
            .satisfies(a ->
                assertThat(a.getMontantHT()).as("check montantHT").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMontantHT())
            )
            .satisfies(a ->
                assertThat(a.getTauxTVA()).as("check tauxTVA").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTauxTVA())
            )
            .satisfies(a ->
                assertThat(a.getMontantTVA())
                    .as("check montantTVA")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantTVA())
            )
            .satisfies(a ->
                assertThat(a.getMontantTTC())
                    .as("check montantTTC")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantTTC())
            )
            .satisfies(a -> assertThat(a.getObservations()).as("check observations").isEqualTo(expected.getObservations()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailFactureEntityUpdatableRelationshipsEquals(DetailFactureEntity expected, DetailFactureEntity actual) {
        assertThat(actual)
            .as("Verify DetailFactureEntity relationships")
            .satisfies(a -> assertThat(a.getFacture()).as("check facture").isEqualTo(expected.getFacture()));
    }
}
