package com.convention.domain;

import static com.convention.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DetailConventionEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailConventionEntityAllPropertiesEquals(DetailConventionEntity expected, DetailConventionEntity actual) {
        assertDetailConventionEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertDetailConventionEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailConventionEntityAllUpdatablePropertiesEquals(
        DetailConventionEntity expected,
        DetailConventionEntity actual
    ) {
        assertDetailConventionEntityUpdatableFieldsEquals(expected, actual);
        assertDetailConventionEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailConventionEntityAutoGeneratedPropertiesEquals(
        DetailConventionEntity expected,
        DetailConventionEntity actual
    ) {
        assertThat(actual)
            .as("Verify DetailConventionEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailConventionEntityUpdatableFieldsEquals(DetailConventionEntity expected, DetailConventionEntity actual) {
        assertThat(actual)
            .as("Verify DetailConventionEntity relevant properties")
            .satisfies(a -> assertThat(a.getDesignation()).as("check designation").isEqualTo(expected.getDesignation()))
            .satisfies(a ->
                assertThat(a.getPrixUnitaire())
                    .as("check prixUnitaire")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrixUnitaire())
            )
            .satisfies(a -> assertThat(a.getQuantite()).as("check quantite").isEqualTo(expected.getQuantite()))
            .satisfies(a ->
                assertThat(a.getMontantTotal())
                    .as("check montantTotal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantTotal())
            )
            .satisfies(a -> assertThat(a.getObservations()).as("check observations").isEqualTo(expected.getObservations()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailConventionEntityUpdatableRelationshipsEquals(
        DetailConventionEntity expected,
        DetailConventionEntity actual
    ) {
        assertThat(actual)
            .as("Verify DetailConventionEntity relationships")
            .satisfies(a -> assertThat(a.getConvention()).as("check convention").isEqualTo(expected.getConvention()));
    }
}
