package com.convention.domain;

import static com.convention.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FactureEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactureEntityAllPropertiesEquals(FactureEntity expected, FactureEntity actual) {
        assertFactureEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertFactureEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactureEntityAllUpdatablePropertiesEquals(FactureEntity expected, FactureEntity actual) {
        assertFactureEntityUpdatableFieldsEquals(expected, actual);
        assertFactureEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactureEntityAutoGeneratedPropertiesEquals(FactureEntity expected, FactureEntity actual) {
        assertThat(actual)
            .as("Verify FactureEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactureEntityUpdatableFieldsEquals(FactureEntity expected, FactureEntity actual) {
        assertThat(actual)
            .as("Verify FactureEntity relevant properties")
            .satisfies(a -> assertThat(a.getNumFacture()).as("check numFacture").isEqualTo(expected.getNumFacture()))
            .satisfies(a -> assertThat(a.getDateFacture()).as("check dateFacture").isEqualTo(expected.getDateFacture()))
            .satisfies(a ->
                assertThat(a.getMontantTotal())
                    .as("check montantTotal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantTotal())
            )
            .satisfies(a ->
                assertThat(a.getMontantTTC())
                    .as("check montantTTC")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantTTC())
            )
            .satisfies(a -> assertThat(a.getTva()).as("check tva").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTva()))
            .satisfies(a -> assertThat(a.getObservations()).as("check observations").isEqualTo(expected.getObservations()))
            .satisfies(a -> assertThat(a.getAncienneRef()).as("check ancienneRef").isEqualTo(expected.getAncienneRef()))
            .satisfies(a -> assertThat(a.getTypeFacture()).as("check typeFacture").isEqualTo(expected.getTypeFacture()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateEcheance()).as("check dateEcheance").isEqualTo(expected.getDateEcheance()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactureEntityUpdatableRelationshipsEquals(FactureEntity expected, FactureEntity actual) {
        assertThat(actual)
            .as("Verify FactureEntity relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()))
            .satisfies(a -> assertThat(a.getConvention()).as("check convention").isEqualTo(expected.getConvention()));
    }
}
